### ISSUE TITLE
Opacity of transitioning images, styling of the section "room service" , navigation links

### ISSUE THREAD

**Issue by Hitanshi-Singh** [abhigyan-c/wanderer#11]
1. In the transitioning images using ::before a black background should be there so that the title written there is visible
2. In the section of room service- changing of line width, colour and adding padding to it.
3. not all the navigation links are changing the arrow to pointer on hovering. correcting that

**Comment by Hitanshi-Singh** [comment]
may i work on these?

**Comment by Tapo41** [comment]
I want to contribute to this

**Comment by satatya** [comment]
@Hitanshi-Singh yes, please go ahead..but leave aside issue no. 2, because someone has already fixed it.. for issue 1, dont make it a black background, instead you may change the text color for visibility, because the opacity of these cards were designed for visual effects in coordination with the team last year.

@Tapo41 if she's working on this issue ,pls raise a different issue and work on it, or go for those issues which are open.

**Comment by Hitanshi-Singh** [comment]
@satatya okay..I'll keep these points in mind while working
